// Run with NODE_PATH pointing to an installation of Playwright.
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const {tmpdir} = require('node:os');
const baseURL = process.env.TEST_BASE_URL || 'http://127.0.0.1:8765';
const screenshotPath = name => path.join(tmpdir(),'abidi-tour-'+name+'.png');
(async () => {
  const executablePath = process.env.CHROME_PATH || (process.platform === 'win32' ? 'C:/Program Files/Google/Chrome/Application/chrome.exe' : undefined);
  const browser = await chromium.launch({executablePath,headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    const errors = [];
    page.on('pageerror',error=>errors.push(error.message));
    await page.goto(baseURL+'/index.html');
    await page.evaluate(()=>localStorage.setItem('abidi-vehicles',JSON.stringify([
      ...window.defaultVehicles,
      {id:999,brand:'Not approved',model:'Extra car',price:1,published:true}
    ])));
    await page.reload();
    assert.equal(await page.locator('.vehicle-card').count(),31,'Saved extra vehicles are rejected');
    assert.equal(await page.locator('#vehicleGrid').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),3,'Desktop catalogue uses three equal columns');
    await page.setViewportSize({width:1365,height:600});
    assert.equal(await page.locator('#vehicleGrid').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),3,'Short desktop viewport keeps three catalogue columns');
    await page.setViewportSize({width:1440,height:1000});
    assert.equal(await page.getByText('Extra car',{exact:true}).count(),0,'Unapproved identity never reaches the catalogue');
    assert.equal(await page.locator('[data-hero-car]').count(),0,'Arrival has no hero car');
    await page.mouse.move(1250,350);
    await page.waitForTimeout(500);
    const look = await page.locator('#home').evaluate(el=>el.style.getPropertyValue('--look-x'));
    assert(Math.abs(parseFloat(look))>1,'Pointer moves the room');
    await page.locator('#tourMotion').click();
    assert.equal(await page.locator('#home').getAttribute('data-motion-paused'),'true');
    await page.screenshot({path:screenshotPath('arrival')});
    await page.locator('#tourMotion').click();
    await page.locator('#tourAction').click();
    await page.waitForTimeout(150);
    await page.waitForTimeout(750);
    assert.equal(await page.locator('#home').getAttribute('data-room'),'passage');
    await page.waitForTimeout(700);
    assert(Math.abs(parseFloat(await page.locator('#home').evaluate(el=>el.style.getPropertyValue('--room-x'))))<.2,'Scroll reaches the walkthrough viewpoint');
    assert((await page.evaluate(()=>scrollY>innerHeight*.7)),'The showroom journey is scroll-scrubbed');
    assert.equal(await page.locator('#tourGallery').isVisible(),false,'Walkthrough remains uncluttered');
    await page.screenshot({path:screenshotPath('walkthrough')});
    await page.locator('#tourAction').click();
    await page.waitForTimeout(1100);
    assert.equal(await page.locator('#home').getAttribute('data-room'),'collection');
    assert.equal(await page.locator('.tour-display').count(),2);
    await page.locator('.tour-display').first().click();
    assert(await page.locator('#vehicleModal').evaluate(el=>el.open),'Gallery opens vehicle details');
    assert.match(await page.locator('#modalContent h2').textContent(),/T-Roc/);
    await page.screenshot({path:screenshotPath('details-360')});
    await page.keyboard.press('Escape');
    await page.screenshot({path:screenshotPath('collection')});
    assert.equal(await page.locator('#tourConcierge').count(),0,'Previous lounge was removed');
    await page.locator('[data-room-target="collection"]').focus();
    await page.keyboard.press('Home');
    await page.waitForTimeout(1100);
    assert.equal(await page.locator('#home').getAttribute('data-room'),'arrival');
    await page.locator('#brandFilter').selectOption('Audi');
    await page.locator('#inventory').scrollIntoViewIfNeeded();
    await page.waitForTimeout(1400);
    assert.equal(await page.locator('.vehicle-card').count(),2);
    assert.equal(await page.locator('.vehicle-card.card-visible').count(),2,'Filtered cards reveal');
    await page.locator('.vehicle-card .vehicle-title').first().click();
    assert(await page.locator('#vehicleModal').evaluate(el=>el.open),'Clicking the card content opens vehicle details');
    await page.screenshot({path:screenshotPath('details-premium')});
    await page.keyboard.press('Escape');
    await page.locator('.vehicle-card').nth(1).focus();
    await page.keyboard.press('Enter');
    assert(await page.locator('#vehicleModal').evaluate(el=>el.open),'A focused card opens with the keyboard');
    await page.keyboard.press('Escape');
    await page.locator('.details-button').first().click();
    assert(await page.locator('#vehicleModal').evaluate(el=>el.open),'Filtered details work');
    await page.keyboard.press('Escape');
    await page.locator('#clearFilters').click();
    assert.equal(await page.locator('.vehicle-card').count(),31,'Only original inventory');
    await page.locator('[data-fav="4"]').click();
    assert.equal(await page.locator('#favoriteCount').textContent(),'1');
    await page.locator('#favoritesButton').click();
    assert.equal(await page.locator('.vehicle-card').count(),1,'Saved vehicle filter works');
    await page.locator('#clearFilters').click();
    await page.locator('[data-compare="4"]').check();
    await page.locator('[data-compare="11"]').check();
    await page.locator('#compareNow').click();
    assert(await page.locator('#compareModal').evaluate(el=>el.open));
    assert.equal(await page.locator('.compare-table thead th').count(),3);
    await page.keyboard.press('Escape');
    await page.locator('#clearCompare').click();
    assert.equal(await page.locator('#compareBar').isVisible(),false,'Cleared comparison stays hidden');
    // Capture the URL locally; never open WhatsApp or send a real enquiry.
    await page.evaluate(()=>{window.open=url=>{window.testWhatsAppURL=url;return null}});
    await page.locator('#contact').scrollIntoViewIfNeeded();
    await page.locator('#contactForm [name="name"]').fill('Browser test');
    await page.locator('#contactForm [name="phone"]').fill('0000000000');
    await page.locator('#contactForm [name="message"]').fill('Local regression check only');
    await page.locator('#contactForm [type="submit"]').click();
    const contactURL = new URL(await page.evaluate(()=>window.testWhatsAppURL));
    assert.equal(contactURL.hostname,'wa.me');
    assert.equal(contactURL.pathname,'/213795263552');
    assert.match(contactURL.searchParams.get('text'),/Local regression check only/);
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.locator('#home').scrollIntoViewIfNeeded();
    assert.equal(await page.locator('#home').getAttribute('data-motion-paused'),'true');
    await page.locator('[data-room-target="collection"]').click();
    assert(await page.locator('#tourGallery').isVisible(),'Reduced motion retains navigation');
    assert.equal(await page.locator('.showroom-tour').evaluate(el=>el.scrollWidth>el.clientWidth),false);
    for (const width of [390,768]) {
      const mobile = await browser.newPage({viewport:{width,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
      mobile.on('pageerror',error=>errors.push(error.message));
      await mobile.goto(baseURL+'/index.html');
      await mobile.waitForSelector('.showroom-tour');
      assert.equal(await mobile.locator('#compareBar').isVisible(),false,'Empty comparison stays hidden with reduced motion');
      assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow at '+width);
      await mobile.locator('#home').screenshot({path:screenshotPath('mobile-'+width)});
      await mobile.locator('#tourAction').tap();
      assert.equal(await mobile.locator('#home').getAttribute('data-room'),'passage');
      assert.equal(await mobile.locator('#tourGallery').isVisible(),false);
      await mobile.locator('#tourAction').tap();
      assert.equal(await mobile.locator('#home').getAttribute('data-room'),'collection');
      await mobile.locator('#home').screenshot({path:screenshotPath('mobile-collection-'+width)});
      await mobile.locator('.tour-display').first().tap();
      assert(await mobile.locator('#vehicleModal').evaluate(el=>el.open));
      await mobile.keyboard.press('Escape');
      await mobile.locator('[data-room-target="arrival"]').tap();
      assert.equal(await mobile.locator('#home').getAttribute('data-room'),'arrival');
      await mobile.locator('.nav-toggle').tap();
      assert.equal(await mobile.locator('.nav-toggle').getAttribute('aria-expanded'),'true');
      await mobile.locator('.main-nav a').first().tap();
      assert.equal(await mobile.locator('.nav-toggle').getAttribute('aria-expanded'),'false');
      await mobile.close();
    }
    await page.goto(baseURL+'/admin.html');
    await page.locator('[data-view="inventory"]').click();
    assert.equal(await page.locator('#adminRows tr').count(),31,'Admin is limited to the approved inventory');
    assert.equal(await page.locator('#addVehicle').count(),0,'Admin cannot add unapproved vehicles');
    await page.locator('[data-edit]').first().click();
    assert(await page.locator('#editForm [name="brand"]').getAttribute('readonly')!==null,'Approved brands are locked');
    assert(await page.locator('#editForm [name="model"]').getAttribute('readonly')!==null,'Approved models are locked');
    await page.keyboard.press('Escape');
    assert.deepEqual(errors,[],'No runtime errors');
    console.log('PASS: clean arrival, scroll-scrubbed room navigation, mouse camera, pause, details, filters, favourites, comparison, WhatsApp URL, reduced motion, touch, mobile menu and overflow.');
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1});
